defaults: 
  - default_training_conf.yaml

seed: 42

model: 
  type: "BiDirectionalSTGNN"
  kwargs: 
    hidden_size: 64
    n_layers: 1
    dropout_p: 0.2
    output_dist: LogNormal

training:
  optim:
    algo: 'RMSprop'
    kwargs:
      lr: 0.0001
      momentum: 0.5