defaults:
  - default_training_conf.yaml

model:
  type: "Model0TCN"
  kwargs:
    hidden_channels: 64
    num_layers: 4
    kernel_size: 3
    dropout_p: 0.2
    output_dist: LogNormal

training:
  optim:
    kwargs:
      lr: 0.0001