defaults:
- default_training_conf.yaml
- _self_
model:
  type: EnhancedTCN_GNN
  kwargs:
    num_layers: 2
    hidden_channels: 64
    kernel_size: 3
    dropout_p: 0.10193091799165682
    causal_conv: false
    output_dist: LogNormal
    learned_adj_emb_size: 10
    gat_heads: 2
training:
  optim:
    kwargs:
      lr: 0.0008718383855080231
  batch_size: 32
seed: 42
