defaults: 
  - default_training_conf.yaml

model: 
  type: "EnhancedBiDirectionalSTGNN"
  kwargs: 
    hidden_size: 64
    num_layers: 2
    dropout_p: 0.10193091799165682
    num_heads: 2
    output_dist: LogNormal

training: 
    algo: 'RMSprop'
    kwargs:
      lr: 0.0008718383855080231
      momentum: 0.5
      weight_decay: 0.0001
    
    batch_size: 16